services:
  ku-clubs-frontend:
    image: jgogo01/472-s-ku-clubs-6510405482:latest
    ports:
      - "3000:3000"
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ku_clubs
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local